## 1. Import Necessary libraries

In [1]:
import pandas as pd

## 2. Import Data

In [4]:
movie_data = pd.read_csv('Movie.csv')
movie_data

userId             movie  rating
0          3  Toy Story (1995)     4.0
1          6  Toy Story (1995)     5.0
2          8  Toy Story (1995)     4.0
3         10  Toy Story (1995)     4.0
4         11  Toy Story (1995)     4.5
...      ...               ...     ...
8987    7087  GoldenEye (1995)     3.0
8988    7088  GoldenEye (1995)     1.0
8989    7105  GoldenEye (1995)     2.0
8990    7113  GoldenEye (1995)     3.0
8991    7117  GoldenEye (1995)     3.0

[8992 rows x 3 columns]

## 3. Data Understanding

In [5]:
movie_data.shape

(8992, 3)

In [6]:
movie_data['userId'].nunique()

4081

In [7]:
movie_data['movie'].nunique()

10

In [8]:
print(movie_data['movie'].unique())

['Toy Story (1995)' 'Jumanji (1995)' 'Grumpier Old Men (1995)'
 'Waiting to Exhale (1995)' 'Father of the Bride Part II (1995)'
 'Heat (1995)' 'Sabrina (1995)' 'Tom and Huck (1995)'
 'Sudden Death (1995)' 'GoldenEye (1995)']


In [9]:
movie_data['userId'].unique()

array([   3,    6,    8, ..., 7080, 7087, 7105], dtype=int64)

In [10]:
movie_data.isna().sum()

userId    0
movie     0
rating    0
dtype: int64

## Provide UBCF

### 1. Use Correlation Matrix as metric for UBCF

In [ ]:
#pd.set_option('max_columns',None)

In [13]:
corr_piv_table = pd.pivot_table(data = movie_data,values='rating',index='movie',columns='userId').fillna(0)
corr_piv_table

userId                              1     2     3     4     5     6     7     \
movie                                                                          
Father of the Bride Part II (1995)   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
GoldenEye (1995)                     0.0   0.0   0.0   4.0   0.0   0.0   0.0   
Grumpier Old Men (1995)              0.0   4.0   0.0   0.0   0.0   3.0   3.0   
Heat (1995)                          0.0   0.0   0.0   3.0   0.0   0.0   0.0   
Jumanji (1995)                       3.5   0.0   0.0   0.0   3.0   0.0   0.0   
Sabrina (1995)                       0.0   0.0   0.0   0.0   0.0   5.0   3.0   
Sudden Death (1995)                  0.0   0.0   0.0   0.0   0.0   0.0   0.0   
Tom and Huck (1995)                  0.0   0.0   0.0   0.0   0.0   0.0   0.0   
Toy Story (1995)                     0.0   0.0   4.0   0.0   0.0   5.0   0.0   
Waiting to Exhale (1995)             0.0   0.0   0.0   0.0   0.0   0.0   0.0   

userId                              8     10    11    ...  7105  7107  7108  \
movie                                                 ...                     
Father of the Bride Part II (1995)   0.0   0.0   0.0  ...   0.0   0.0   0.0   
GoldenEye (1995)                     4.0   0.0   2.5  ...   2.0   0.0   0.0   
Grumpier Old Men (1995)              5.0   0.0   0.0  ...   0.0   0.0   0.0   
Heat (1995)                          3.0   0.0   0.0  ...   0.0   0.0   0.0   
Jumanji (1995)                       0.0   0.0   0.0  ...   0.0   0.0   2.0   
Sabrina (1995)                       0.0   0.0   0.0  ...   0.0   0.0   0.0   
Sudden Death (1995)                  0.0   0.0   0.0  ...   0.0   0.0   0.0   
Tom and Huck (1995)                  0.0   0.0   0.0  ...   0.0   0.0   0.0   
Toy Story (1995)                     4.0   4.0   4.5  ...   0.0   4.0   0.0   
Waiting to Exhale (1995)             0.0   0.0   0.0  ...   0.0   0.0   0.0   

userId                              7110  7113  7115  7116  7117  7119  7120  
movie                                                                         
Father of the Bride Part II (1995)   0.0   0.0   4.0   3.5   0.0   0.0   0.0  
GoldenEye (1995)                     0.0   3.0   0.0   0.0   3.0   0.0   0.0  
Grumpier Old Men (1995)              0.0   0.0   0.0   0.0   4.0   0.0   0.0  
Heat (1995)                          0.0   3.0   0.0   0.0   5.0   0.0   0.0  
Jumanji (1995)                       4.0   0.0   0.0   0.0   0.0   0.0   4.0  
Sabrina (1995)                       0.0   0.0   0.0   0.0   3.0   0.0   4.0  
Sudden Death (1995)                  0.0   0.0   0.0   0.0   1.0   0.0   0.0  
Tom and Huck (1995)                  0.0   0.0   0.0   0.0   0.0   0.0   0.0  
Toy Story (1995)                     4.0   0.0   0.0   4.0   4.0   5.0   4.5  
Waiting to Exhale (1995)             0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[10 rows x 4081 columns]

In [16]:
corr_piv_table.columns = movie_data['userId'].unique()
corr_piv_table

3     6     8     10    11    12    13    \
movie                                                                          
Father of the Bride Part II (1995)   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
GoldenEye (1995)                     0.0   0.0   0.0   4.0   0.0   0.0   0.0   
Grumpier Old Men (1995)              0.0   4.0   0.0   0.0   0.0   3.0   3.0   
Heat (1995)                          0.0   0.0   0.0   3.0   0.0   0.0   0.0   
Jumanji (1995)                       3.5   0.0   0.0   0.0   3.0   0.0   0.0   
Sabrina (1995)                       0.0   0.0   0.0   0.0   0.0   5.0   3.0   
Sudden Death (1995)                  0.0   0.0   0.0   0.0   0.0   0.0   0.0   
Tom and Huck (1995)                  0.0   0.0   0.0   0.0   0.0   0.0   0.0   
Toy Story (1995)                     0.0   0.0   4.0   0.0   0.0   5.0   0.0   
Waiting to Exhale (1995)             0.0   0.0   0.0   0.0   0.0   0.0   0.0   

                                    14    16    19    ...  6975  6979  6993  \
movie                                                 ...                     
Father of the Bride Part II (1995)   0.0   0.0   0.0  ...   0.0   0.0   0.0   
GoldenEye (1995)                     4.0   0.0   2.5  ...   2.0   0.0   0.0   
Grumpier Old Men (1995)              5.0   0.0   0.0  ...   0.0   0.0   0.0   
Heat (1995)                          3.0   0.0   0.0  ...   0.0   0.0   0.0   
Jumanji (1995)                       0.0   0.0   0.0  ...   0.0   0.0   2.0   
Sabrina (1995)                       0.0   0.0   0.0  ...   0.0   0.0   0.0   
Sudden Death (1995)                  0.0   0.0   0.0  ...   0.0   0.0   0.0   
Tom and Huck (1995)                  0.0   0.0   0.0  ...   0.0   0.0   0.0   
Toy Story (1995)                     4.0   4.0   4.5  ...   0.0   4.0   0.0   
Waiting to Exhale (1995)             0.0   0.0   0.0  ...   0.0   0.0   0.0   

                                    7030  7031  7044  7070  7080  7087  7105  
movie                                                                         
Father of the Bride Part II (1995)   0.0   0.0   4.0   3.5   0.0   0.0   0.0  
GoldenEye (1995)                     0.0   3.0   0.0   0.0   3.0   0.0   0.0  
Grumpier Old Men (1995)              0.0   0.0   0.0   0.0   4.0   0.0   0.0  
Heat (1995)                          0.0   3.0   0.0   0.0   5.0   0.0   0.0  
Jumanji (1995)                       4.0   0.0   0.0   0.0   0.0   0.0   4.0  
Sabrina (1995)                       0.0   0.0   0.0   0.0   3.0   0.0   4.0  
Sudden Death (1995)                  0.0   0.0   0.0   0.0   1.0   0.0   0.0  
Tom and Huck (1995)                  0.0   0.0   0.0   0.0   0.0   0.0   0.0  
Toy Story (1995)                     4.0   0.0   0.0   4.0   4.0   5.0   4.5  
Waiting to Exhale (1995)             0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[10 rows x 4081 columns]

In [18]:
corr_piv_table.corr().round(2)

3     6     8     10    11    12    13    14    16    19    ...  6975  \
3     1.00 -0.11 -0.11 -0.16  1.00 -0.21 -0.17 -0.27 -0.11 -0.16  ... -0.11   
6    -0.11  1.00 -0.11 -0.16 -0.11  0.28  0.67  0.56 -0.11 -0.16  ... -0.11   
8    -0.11 -0.11  1.00 -0.16 -0.11  0.60 -0.17  0.40  1.00  0.86  ... -0.11   
10   -0.16 -0.16 -0.16  1.00 -0.16 -0.31 -0.25  0.48 -0.16  0.24  ...  0.78   
11    1.00 -0.11 -0.11 -0.16  1.00 -0.21 -0.17 -0.27 -0.11 -0.16  ... -0.11   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
7044 -0.11 -0.11 -0.11 -0.16 -0.11 -0.21 -0.17 -0.27 -0.11 -0.16  ... -0.11   
7070 -0.17 -0.17  0.72 -0.25 -0.17  0.33 -0.25  0.13  0.72  0.58  ... -0.17   
7080 -0.35  0.35  0.35  0.48 -0.35  0.54  0.40  0.81  0.35  0.41  ...  0.18   
7087 -0.11 -0.11  1.00 -0.16 -0.11  0.60 -0.17  0.40  1.00  0.86  ... -0.11   
7105  0.48 -0.22  0.57 -0.32  0.48  0.67  0.20 -0.05  0.57  0.41  ... -0.22   

      6979  6993  7030  7031  7044  7070  7080  7087  7105  
3    -0.11  1.00  0.67 -0.17 -0.11 -0.17 -0.35 -0.11  0.48  
6    -0.11 -0.11 -0.17 -0.17 -0.11 -0.17  0.35 -0.11 -0.22  
8     1.00 -0.11  0.67 -0.17 -0.11  0.72  0.35  1.00  0.57  
10   -0.16 -0.16 -0.25  0.99 -0.16 -0.25  0.48 -0.16 -0.32  
11   -0.11  1.00  0.67 -0.17 -0.11 -0.17 -0.35 -0.11  0.48  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
7044 -0.11 -0.11 -0.17 -0.17  1.00  0.61 -0.35 -0.11 -0.22  
7070  0.72 -0.17  0.42 -0.25  0.61  1.00  0.04  0.72  0.30  
7080  0.35 -0.35  0.00  0.53 -0.35  0.04  1.00  0.35  0.14  
7087  1.00 -0.11  0.67 -0.17 -0.11  0.72  0.35  1.00  0.57  
7105  0.57  0.48  0.78 -0.33 -0.22  0.30  0.14  0.57  1.00  

[4081 rows x 4081 columns]

### 2. Use Euclideon Distance as a Metric for UBCF

In [20]:
movie_data.columns

Index(['userId', 'movie', 'rating'], dtype='object')

In [19]:
from sklearn.metrics import pairwise_distances

In [22]:
euclideon_pivot_table = pd.pivot_table(data = movie_data,values='rating',index='userId',columns='movie').fillna(0)
euclideon_pivot_table

movie   Father of the Bride Part II (1995)  GoldenEye (1995)  \
userId                                                         
1                                      0.0               0.0   
2                                      0.0               0.0   
3                                      0.0               0.0   
4                                      0.0               4.0   
5                                      0.0               0.0   
...                                    ...               ...   
7115                                   4.0               0.0   
7116                                   3.5               0.0   
7117                                   0.0               3.0   
7119                                   0.0               0.0   
7120                                   0.0               0.0   

movie   Grumpier Old Men (1995)  Heat (1995)  Jumanji (1995)  Sabrina (1995)  \
userId                                                                         
1                           0.0          0.0             3.5             0.0   
2                           4.0          0.0             0.0             0.0   
3                           0.0          0.0             0.0             0.0   
4                           0.0          3.0             0.0             0.0   
5                           0.0          0.0             3.0             0.0   
...                         ...          ...             ...             ...   
7115                        0.0          0.0             0.0             0.0   
7116                        0.0          0.0             0.0             0.0   
7117                        4.0          5.0             0.0             3.0   
7119                        0.0          0.0             0.0             0.0   
7120                        0.0          0.0             4.0             4.0   

movie   Sudden Death (1995)  Tom and Huck (1995)  Toy Story (1995)  \
userId                                                               
1                       0.0                  0.0               0.0   
2                       0.0                  0.0               0.0   
3                       0.0                  0.0               4.0   
4                       0.0                  0.0               0.0   
5                       0.0                  0.0               0.0   
...                     ...                  ...               ...   
7115                    0.0                  0.0               0.0   
7116                    0.0                  0.0               4.0   
7117                    1.0                  0.0               4.0   
7119                    0.0                  0.0               5.0   
7120                    0.0                  0.0               4.5   

movie   Waiting to Exhale (1995)  
userId                            
1                            0.0  
2                            0.0  
3                            0.0  
4                            0.0  
5                            0.0  
...                          ...  
7115                         0.0  
7116                         0.0  
7117                         0.0  
7119                         0.0  
7120                         0.0  

[4081 rows x 10 columns]

In [24]:
movie_data['userId'].unique()

array([   3,    6,    8, ..., 7080, 7087, 7105], dtype=int64)

In [25]:
euclideon_pivot_table.index = movie_data['userId'].unique()
euclideon_pivot_table

movie  Father of the Bride Part II (1995)  GoldenEye (1995)  \
3                                     0.0               0.0   
6                                     0.0               0.0   
8                                     0.0               0.0   
10                                    0.0               4.0   
11                                    0.0               0.0   
...                                   ...               ...   
7044                                  4.0               0.0   
7070                                  3.5               0.0   
7080                                  0.0               3.0   
7087                                  0.0               0.0   
7105                                  0.0               0.0   

movie  Grumpier Old Men (1995)  Heat (1995)  Jumanji (1995)  Sabrina (1995)  \
3                          0.0          0.0             3.5             0.0   
6                          4.0          0.0             0.0             0.0   
8                          0.0          0.0             0.0             0.0   
10                         0.0          3.0             0.0             0.0   
11                         0.0          0.0             3.0             0.0   
...                        ...          ...             ...             ...   
7044                       0.0          0.0             0.0             0.0   
7070                       0.0          0.0             0.0             0.0   
7080                       4.0          5.0             0.0             3.0   
7087                       0.0          0.0             0.0             0.0   
7105                       0.0          0.0             4.0             4.0   

movie  Sudden Death (1995)  Tom and Huck (1995)  Toy Story (1995)  \
3                      0.0                  0.0               0.0   
6                      0.0                  0.0               0.0   
8                      0.0                  0.0               4.0   
10                     0.0                  0.0               0.0   
11                     0.0                  0.0               0.0   
...                    ...                  ...               ...   
7044                   0.0                  0.0               0.0   
7070                   0.0                  0.0               4.0   
7080                   1.0                  0.0               4.0   
7087                   0.0                  0.0               5.0   
7105                   0.0                  0.0               4.5   

movie  Waiting to Exhale (1995)  
3                           0.0  
6                           0.0  
8                           0.0  
10                          0.0  
11                          0.0  
...                         ...  
7044                        0.0  
7070                        0.0  
7080                        0.0  
7087                        0.0  
7105                        0.0  

[4081 rows x 10 columns]

In [26]:
euclideon_pivot_table.values

array([[0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 4. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 4. , 0. ],
       ...,
       [0. , 3. , 4. , ..., 0. , 4. , 0. ],
       [0. , 0. , 0. , ..., 0. , 5. , 0. ],
       [0. , 0. , 0. , ..., 0. , 4.5, 0. ]])

In [27]:
euclideon_ubcf = pairwise_distances(X =euclideon_pivot_table.values,metric='euclidean')
euclideon_ubcf

array([[0.        , 5.31507291, 5.31507291, ..., 9.39414711, 6.10327781,
        6.04152299],
       [5.31507291, 0.        , 5.65685425, ..., 7.74596669, 6.40312424,
        8.26135582],
       [5.31507291, 5.65685425, 0.        , ..., 7.74596669, 1.        ,
        5.67890835],
       ...,
       [9.39414711, 7.74596669, 7.74596669, ..., 0.        , 7.81024968,
        8.26135582],
       [6.10327781, 6.40312424, 1.        , ..., 7.81024968, 0.        ,
        5.67890835],
       [6.04152299, 8.26135582, 5.67890835, ..., 8.26135582, 5.67890835,
        0.        ]])

In [30]:
movie_data['userId'].unique()

array([   3,    6,    8, ..., 7080, 7087, 7105], dtype=int64)

In [33]:
ubcf_euclideon_metric         = pd.DataFrame(data = euclideon_ubcf)
ubcf_euclideon_metric.index   = movie_data['userId'].unique()
ubcf_euclideon_metric.columns = movie_data['userId'].unique()
ubcf_euclideon_metric.round(2)

3     6     8     10    11    12    13    14    16    19    ...  6975  \
3     0.00  5.32  5.32  6.10  0.50  8.44  5.50  8.85  5.32  6.22  ...  4.03   
6     5.32  0.00  5.66  6.40  5.00  7.14  3.16  6.48  5.66  6.52  ...  4.47   
8     5.32  5.66  0.00  6.40  5.00  5.92  5.83  7.07  0.00  2.55  ...  4.47   
10    6.10  6.40  6.40  0.00  5.83  9.17  6.56  6.40  6.40  5.61  ...  3.61   
11    0.50  5.00  5.00  5.83  0.00  8.25  5.20  8.66  5.00  5.96  ...  3.61   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
7044  5.32  5.66  5.66  6.40  5.00  8.66  5.83  9.06  5.66  6.52  ...  4.47   
7070  6.36  6.65  3.50  7.30  6.10  6.87  6.80  7.89  3.50  4.33  ...  5.68   
7080  9.39  7.75  7.75  6.86  9.22  6.40  7.21  4.00  7.75  7.18  ...  8.25   
7087  6.10  6.40  1.00  7.07  5.83  5.83  6.56  7.14  1.00  2.55  ...  5.39   
7105  6.04  8.26  5.68  8.79  6.10  5.12  6.80  9.07  5.68  6.18  ...  7.50   

      6979  6993  7030  7031  7044  7070  7080  7087  7105  
3     5.32  1.50  4.03  5.50  5.32  6.36  9.39  6.10  6.04  
6     5.66  4.47  6.93  5.83  5.66  6.65  7.75  6.40  8.26  
8     0.00  4.47  4.00  5.83  5.66  3.50  7.75  1.00  5.68  
10    6.40  5.39  7.55  1.00  6.40  7.30  6.86  7.07  8.79  
11    5.00  1.00  4.12  5.20  5.00  6.10  9.22  5.83  6.10  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
7044  5.66  4.47  6.93  5.83  0.00  4.03  9.59  6.40  8.26  
7070  3.50  5.68  5.32  6.80  4.03  0.00  8.50  3.64  6.67  
7080  7.75  8.94  8.72  6.78  9.59  8.50  0.00  7.81  8.26  
7087  1.00  5.39  4.12  6.56  6.40  3.64  7.81  0.00  5.68  
7105  5.68  6.34  4.03  8.38  8.26  6.67  8.26  5.68  0.00  

[4081 rows x 4081 columns]

### 3. Use Cosine as a metric for UBCF

In [35]:
cosine_pivot_table = pd.pivot_table(data = movie_data,values='rating',index='userId',columns='movie').fillna(0)
cosine_pivot_table

movie   Father of the Bride Part II (1995)  GoldenEye (1995)  \
userId                                                         
1                                      0.0               0.0   
2                                      0.0               0.0   
3                                      0.0               0.0   
4                                      0.0               4.0   
5                                      0.0               0.0   
...                                    ...               ...   
7115                                   4.0               0.0   
7116                                   3.5               0.0   
7117                                   0.0               3.0   
7119                                   0.0               0.0   
7120                                   0.0               0.0   

movie   Grumpier Old Men (1995)  Heat (1995)  Jumanji (1995)  Sabrina (1995)  \
userId                                                                         
1                           0.0          0.0             3.5             0.0   
2                           4.0          0.0             0.0             0.0   
3                           0.0          0.0             0.0             0.0   
4                           0.0          3.0             0.0             0.0   
5                           0.0          0.0             3.0             0.0   
...                         ...          ...             ...             ...   
7115                        0.0          0.0             0.0             0.0   
7116                        0.0          0.0             0.0             0.0   
7117                        4.0          5.0             0.0             3.0   
7119                        0.0          0.0             0.0             0.0   
7120                        0.0          0.0             4.0             4.0   

movie   Sudden Death (1995)  Tom and Huck (1995)  Toy Story (1995)  \
userId                                                               
1                       0.0                  0.0               0.0   
2                       0.0                  0.0               0.0   
3                       0.0                  0.0               4.0   
4                       0.0                  0.0               0.0   
5                       0.0                  0.0               0.0   
...                     ...                  ...               ...   
7115                    0.0                  0.0               0.0   
7116                    0.0                  0.0               4.0   
7117                    1.0                  0.0               4.0   
7119                    0.0                  0.0               5.0   
7120                    0.0                  0.0               4.5   

movie   Waiting to Exhale (1995)  
userId                            
1                            0.0  
2                            0.0  
3                            0.0  
4                            0.0  
5                            0.0  
...                          ...  
7115                         0.0  
7116                         0.0  
7117                         0.0  
7119                         0.0  
7120                         0.0  

[4081 rows x 10 columns]

In [36]:
cosine_pivot_table.index = movie_data['userId'].unique()
cosine_pivot_table

movie  Father of the Bride Part II (1995)  GoldenEye (1995)  \
3                                     0.0               0.0   
6                                     0.0               0.0   
8                                     0.0               0.0   
10                                    0.0               4.0   
11                                    0.0               0.0   
...                                   ...               ...   
7044                                  4.0               0.0   
7070                                  3.5               0.0   
7080                                  0.0               3.0   
7087                                  0.0               0.0   
7105                                  0.0               0.0   

movie  Grumpier Old Men (1995)  Heat (1995)  Jumanji (1995)  Sabrina (1995)  \
3                          0.0          0.0             3.5             0.0   
6                          4.0          0.0             0.0             0.0   
8                          0.0          0.0             0.0             0.0   
10                         0.0          3.0             0.0             0.0   
11                         0.0          0.0             3.0             0.0   
...                        ...          ...             ...             ...   
7044                       0.0          0.0             0.0             0.0   
7070                       0.0          0.0             0.0             0.0   
7080                       4.0          5.0             0.0             3.0   
7087                       0.0          0.0             0.0             0.0   
7105                       0.0          0.0             4.0             4.0   

movie  Sudden Death (1995)  Tom and Huck (1995)  Toy Story (1995)  \
3                      0.0                  0.0               0.0   
6                      0.0                  0.0               0.0   
8                      0.0                  0.0               4.0   
10                     0.0                  0.0               0.0   
11                     0.0                  0.0               0.0   
...                    ...                  ...               ...   
7044                   0.0                  0.0               0.0   
7070                   0.0                  0.0               4.0   
7080                   1.0                  0.0               4.0   
7087                   0.0                  0.0               5.0   
7105                   0.0                  0.0               4.5   

movie  Waiting to Exhale (1995)  
3                           0.0  
6                           0.0  
8                           0.0  
10                          0.0  
11                          0.0  
...                         ...  
7044                        0.0  
7070                        0.0  
7080                        0.0  
7087                        0.0  
7105                        0.0  

[4081 rows x 10 columns]

In [37]:
cosine_pivot_table.values

array([[0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 4. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 4. , 0. ],
       ...,
       [0. , 3. , 4. , ..., 0. , 4. , 0. ],
       [0. , 0. , 0. , ..., 0. , 5. , 0. ],
       [0. , 0. , 0. , ..., 0. , 4.5, 0. ]])

In [44]:
cosine_ubcf = 1 - pairwise_distances(X = cosine_pivot_table.values,metric='cosine')
cosine_ubcf

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.55337157],
       [0.        , 1.        , 0.        , ..., 0.45883147, 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.45883147, 1.        ,
        0.62254302],
       ...,
       [0.        , 0.45883147, 0.45883147, ..., 1.        , 0.45883147,
        0.47607054],
       [0.        , 0.        , 1.        , ..., 0.45883147, 1.        ,
        0.62254302],
       [0.55337157, 0.        , 0.62254302, ..., 0.47607054, 0.62254302,
        1.        ]])

In [42]:
movie_data['userId'].unique()

array([   3,    6,    8, ..., 7080, 7087, 7105], dtype=int64)

In [46]:
cosine_ubcf_df         = pd.DataFrame(data=cosine_ubcf)
cosine_ubcf_df.index   = movie_data['userId'].unique()
cosine_ubcf_df.columns = movie_data['userId'].unique()
cosine_ubcf_df.round(2)

3     6     8     10    11    12    13    14    16    19    ...  6975  \
3     1.00  0.00  0.00  0.00  1.00  0.00  0.00  0.00  0.00  0.00  ...  0.00   
6     0.00  1.00  0.00  0.00  0.00  0.39  0.71  0.62  0.00  0.00  ...  0.00   
8     0.00  0.00  1.00  0.00  0.00  0.65  0.00  0.49  1.00  0.87  ...  0.00   
10    0.00  0.00  0.00  1.00  0.00  0.00  0.00  0.62  0.00  0.39  ...  0.80   
11    1.00  0.00  0.00  0.00  1.00  0.00  0.00  0.00  0.00  0.00  ...  0.00   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
7044  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.00   
7070  0.00  0.00  0.75  0.00  0.00  0.49  0.00  0.37  0.75  0.66  ...  0.00   
7080  0.00  0.46  0.46  0.62  0.00  0.70  0.57  0.89  0.46  0.57  ...  0.34   
7087  0.00  0.00  1.00  0.00  0.00  0.65  0.00  0.49  1.00  0.87  ...  0.00   
7105  0.55  0.00  0.62  0.00  0.55  0.77  0.39  0.31  0.62  0.54  ...  0.00   

      6979  6993  7030  7031  7044  7070  7080  7087  7105  
3     0.00  1.00  0.71  0.00  0.00  0.00  0.00  0.00  0.55  
6     0.00  0.00  0.00  0.00  0.00  0.00  0.46  0.00  0.00  
8     1.00  0.00  0.71  0.00  0.00  0.75  0.46  1.00  0.62  
10    0.00  0.00  0.00  0.99  0.00  0.00  0.62  0.00  0.00  
11    0.00  1.00  0.71  0.00  0.00  0.00  0.00  0.00  0.55  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
7044  0.00  0.00  0.00  0.00  1.00  0.66  0.00  0.00  0.00  
7070  0.75  0.00  0.53  0.00  0.66  1.00  0.35  0.75  0.47  
7080  0.46  0.00  0.32  0.65  0.00  0.35  1.00  0.46  0.48  
7087  1.00  0.00  0.71  0.00  0.00  0.75  0.46  1.00  0.62  
7105  0.62  0.55  0.83  0.00  0.00  0.47  0.48  0.62  1.00  

[4081 rows x 4081 columns]

### Filter the data top 50users

In [55]:
first_50_users = cosine_ubcf_df.iloc[:50,:50]
first_50_users

3         6         8         10        11        12        13   \
3    0.000000  0.000000  0.000000  0.000000  1.000000  0.000000  0.000000   
6    0.000000  0.000000  0.000000  0.000000  0.000000  0.390567  0.707107   
8    0.000000  0.000000  0.000000  0.000000  0.000000  0.650945  0.000000   
10   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
11   1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
12   0.000000  0.390567  0.650945  0.000000  0.000000  0.000000  0.736460   
13   0.000000  0.707107  0.000000  0.000000  0.000000  0.736460  0.000000   
14   0.000000  0.615457  0.492366  0.615457  0.000000  0.560880  0.435194   
16   0.000000  0.000000  1.000000  0.000000  0.000000  0.650945  0.000000   
19   0.000000  0.000000  0.874157  0.388514  0.000000  0.569028  0.000000   
22   0.000000  0.437595  0.583460  0.262557  0.000000  0.835560  0.618853   
23   0.514496  0.000000  0.685994  0.411597  0.514496  0.446544  0.000000   
24   0.000000  0.000000  0.789352  0.000000  0.000000  0.913466  0.434122   
31   0.000000  0.000000  0.000000  0.800000  0.000000  0.000000  0.000000   
34   0.000000  0.000000  0.707107  0.424264  0.000000  0.460287  0.000000   
39   0.000000  0.000000  0.000000  0.600000  0.000000  0.000000  0.000000   
47   0.000000  0.419314  0.524142  0.314485  0.000000  0.846145  0.667124   
53   0.000000  0.000000  0.000000  0.600000  0.000000  0.000000  0.000000   
54   0.000000  0.000000  0.514496  0.514496  0.000000  0.334908  0.000000   
58   0.000000  0.000000  1.000000  0.000000  0.000000  0.650945  0.000000   
59   0.000000  0.000000  0.544331  0.653197  0.000000  0.620076  0.288675   
66   0.000000  0.000000  0.000000  0.800000  0.000000  0.000000  0.000000   
69   0.600000  0.000000  0.000000  0.000000  0.600000  0.000000  0.000000   
80   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
82   0.000000  0.000000  1.000000  0.000000  0.000000  0.650945  0.000000   
84   0.000000  0.000000  0.000000  0.989949  0.000000  0.000000  0.000000   
90   0.363803  0.000000  0.606339  0.485071  0.363803  0.631509  0.257248   
91   0.000000  0.457496  0.000000  0.000000  0.000000  0.675023  0.862662   
93   0.000000  0.000000  0.707107  0.424264  0.000000  0.460287  0.000000   
96   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
97   0.000000  0.000000  0.000000  0.332820  0.000000  0.000000  0.000000   
99   0.000000  0.000000  1.000000  0.000000  0.000000  0.650945  0.000000   
105  0.000000  0.000000  0.000000  0.600000  0.000000  0.000000  0.000000   
107  0.000000  0.000000  1.000000  0.000000  0.000000  0.650945  0.000000   
109  0.390567  0.000000  0.520756  0.650945  0.390567  0.338983  0.000000   
114  0.000000  0.000000  0.743294  0.401379  0.000000  0.483843  0.000000   
115  0.000000  0.000000  1.000000  0.000000  0.000000  0.650945  0.000000   
116  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
117  0.000000  0.000000  1.000000  0.000000  0.000000  0.650945  0.000000   
124  0.000000  0.000000  0.000000  0.800000  0.000000  0.000000  0.000000   
126  0.000000  0.000000  0.000000  0.800000  0.000000  0.000000  0.000000   
129  0.000000  0.000000  0.520756  0.624907  0.000000  0.338983  0.000000   
130  0.000000  0.000000  0.000000  0.854199  0.000000  0.000000  0.000000   
131  0.000000  0.600000  0.000000  0.640000  0.000000  0.234340  0.424264   
133  0.000000  0.577350  0.577350  0.000000  0.000000  0.977140  0.816497   
134  0.000000  0.000000  1.000000  0.000000  0.000000  0.650945  0.000000   
135  0.000000  0.000000  1.000000  0.000000  0.000000  0.650945  0.000000   
136  0.707107  0.000000  0.000000  0.000000  0.707107  0.460287  0.500000   
137  0.000000  0.000000  0.707107  0.565685  0.000000  0.460287  0.000000   
140  0.453743  0.388922  0.518563  0.414850  0.453743  0.700428  0.504184   

          14        16        19   ...       126       129       130  \
3    0.000

In [53]:
import numpy as np
np.fill_diagonal(a = first_50_users.to_numpy(), val = 0)

AttributeError: 'NoneType' object has no attribute 'to_numpy'

In [57]:
first_50_users = cosine_ubcf_df.iloc[:50,:50]
first_50_users.round(2)

3     6     8     10    11    12    13    14    16    19   ...   126  \
3    0.00  0.00  0.00  0.00  1.00  0.00  0.00  0.00  0.00  0.00  ...  0.00   
6    0.00  0.00  0.00  0.00  0.00  0.39  0.71  0.62  0.00  0.00  ...  0.00   
8    0.00  0.00  0.00  0.00  0.00  0.65  0.00  0.49  1.00  0.87  ...  0.00   
10   0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.62  0.00  0.39  ...  0.80   
11   1.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.00   
12   0.00  0.39  0.65  0.00  0.00  0.00  0.74  0.56  0.65  0.57  ...  0.00   
13   0.00  0.71  0.00  0.00  0.00  0.74  0.00  0.44  0.00  0.00  ...  0.00   
14   0.00  0.62  0.49  0.62  0.00  0.56  0.44  0.00  0.49  0.67  ...  0.49   
16   0.00  0.00  1.00  0.00  0.00  0.65  0.00  0.49  0.00  0.87  ...  0.00   
19   0.00  0.00  0.87  0.39  0.00  0.57  0.00  0.67  0.87  0.00  ...  0.49   
22   0.00  0.44  0.58  0.26  0.00  0.84  0.62  0.72  0.58  0.51  ...  0.00   
23   0.51  0.00  0.69  0.41  0.51  0.45  0.00  0.59  0.69  0.85  ...  0.51   
24   0.00  0.00  0.79  0.00  0.00  0.91  0.43  0.39  0.79  0.69  ...  0.00   
31   0.00  0.00  0.00  0.80  0.00  0.00  0.00  0.49  0.00  0.49  ...  1.00   
34   0.00  0.00  0.71  0.42  0.00  0.46  0.00  0.61  0.71  0.62  ...  0.00   
39   0.00  0.00  0.00  0.60  0.00  0.00  0.00  0.37  0.00  0.00  ...  0.00   
47   0.00  0.42  0.52  0.31  0.00  0.85  0.67  0.71  0.52  0.46  ...  0.00   
53   0.00  0.00  0.00  0.60  0.00  0.00  0.00  0.37  0.00  0.00  ...  0.00   
54   0.00  0.00  0.51  0.51  0.00  0.33  0.00  0.57  0.51  0.45  ...  0.00   
58   0.00  0.00  1.00  0.00  0.00  0.65  0.00  0.49  1.00  0.87  ...  0.00   
59   0.00  0.00  0.54  0.65  0.00  0.62  0.29  0.67  0.54  0.67  ...  0.41   
66   0.00  0.00  0.00  0.80  0.00  0.00  0.00  0.49  0.00  0.49  ...  1.00   
69   0.60  0.00  0.00  0.00  0.60  0.00  0.00  0.00  0.00  0.00  ...  0.00   
80   0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.00   
82   0.00  0.00  1.00  0.00  0.00  0.65  0.00  0.49  1.00  0.87  ...  0.00   
84   0.00  0.00  0.00  0.99  0.00  0.00  0.00  0.61  0.00  0.34  ...  0.71   
90   0.36  0.00  0.61  0.49  0.36  0.63  0.26  0.60  0.61  0.82  ...  0.61   
91   0.00  0.46  0.00  0.00  0.00  0.68  0.86  0.28  0.00  0.00  ...  0.00   
93   0.00  0.00  0.71  0.42  0.00  0.46  0.00  0.61  0.71  0.62  ...  0.00   
96   0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.00   
97   0.00  0.00  0.00  0.33  0.00  0.00  0.00  0.20  0.00  0.00  ...  0.00   
99   0.00  0.00  1.00  0.00  0.00  0.65  0.00  0.49  1.00  0.87  ...  0.00   
105  0.00  0.00  0.00  0.60  0.00  0.00  0.00  0.37  0.00  0.00  ...  0.00   
107  0.00  0.00  1.00  0.00  0.00  0.65  0.00  0.49  1.00  0.87  ...  0.00   
109  0.39  0.00  0.52  0.65  0.39  0.34  0.00  0.66  0.52  0.71  ...  0.52   
114  0.00  0.00  0.74  0.40  0.00  0.48  0.00  0.61  0.74  0.65  ...  0.00   
115  0.00  0.00  1.00  0.00  0.00  0.65  0.00  0.49  1.00  0.87  ...  0.00   
116  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.00   
117  0.00  0.00  1.00  0.00  0.00  0.65  0.00  0.49  1.00  0.87  ...  0.00   
124  0.00  0.00  0.00  0.80  0.00  0.00  0.00  0.49  0.00  0.49  ...  1.00   
126  0.00  0.00  0.00  0.80  0.00  0.00  0.00  0.49  0.00  0.49  ...  0.00   
129  0.00  0.00  0.52  0.62  0.00  0.34  0.00  0.64  0.52  0.64  ...  0.39   
130  0.00  0.00  0.00  0.85  0.00  0.00  0.00  0.53  0.00  0.18  ...  0.37   
131  0.00  0.60  0.00  0.64  0.00  0.23  0.42  0.76  0.00  0.39  ...  0.80   
133  0.00  0.58  0.58  0.00  0.00  0.98  0.82  0.64  0.58  0.50  ...  0.00   
134  0.00  0.00  1.00  0.00  0.00  0.65  0.00  0.49  1.00  0.87  ...  0.00   
135  0.00  0.00  1.00  0.00  0.00  0.65  0.00  0.49  1.00  0.87  ...  0.00   
136  0.71  0.00  0.00  0.00  0.71  0.46  0.50  0.00  0.00  0.00  ...  0.00   
137  0.00  0.00  0.71  0.57  0.00  0.46  0.00  0.70  0.71  0.96  ...  0.71   
140  0.45  0.39  0.52  0.41  0.45  0.70  0.50  0.75  0.52  0.71  ...  0.52   

      129   130   131   133

In [59]:
first_50_users.idxmax()
#Return index of first occurrence of maximum over requested axis.

3       11
6       13
8       16
10      84
11       3
12     133
13      91
14     131
16       8
19     137
22      47
23      90
24      12
31      66
34      93
39      53
47      22
53      39
54      34
58       8
59     129
66      31
69       3
80      97
82       8
84      10
90      23
91      13
93      34
96     116
97      80
99       8
105     39
107      8
109    129
114     34
115      8
116     96
117      8
124     31
126     31
129     59
130     39
131     31
133     12
134      8
135      8
136      3
137     19
140     90
dtype: int64

In [64]:
movie_data[(movie_data['userId'] == 140) | (movie_data['userId']==90)]

userId                               movie  rating
26        90                    Toy Story (1995)     3.5
49       140                    Toy Story (1995)     4.0
4556     140  Father of the Bride Part II (1995)     3.0
5232     140                         Heat (1995)     4.0
7459      90                    GoldenEye (1995)     3.5
7467     140                    GoldenEye (1995)     4.0

### Inference

**Here 90th User and 140th user are highly correlated. So the movies watched by 140th usr will be recommended/shared to 90th user.**

# THE END.